2-е задание
js-tasks-ru/js-20230223_evss-site pull request #2
Opened 2023-03-04 07:54 UTC by e-free

2023-03-04 07:55 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-05 05:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-03-05 10:54 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const arr = path.split('.');
👍 good 
лайк за использование замыкания

2023-03-05 10:54 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      return subObject === undefined ? subObject : getter(subObject);
👍 good 
лайк за рекурсию

2023-03-05 10:57 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  return getter;
В решении есть проблема, и проблема достаточно существенная.
Попробуйте вызвать эту ф-ции дважды:
```js
const getter = createGetter('foo.bar');

getter({foo: { bar: 1 }}); // 1
getter({foo: { bar: 1 }}); // ?
```
что вернется во втором случае? почему?

2023-03-05 10:57 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return Object.fromEntries(
good 👍

2023-03-05 10:57 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
>  export function trimSymbols(string, size) {
good 👍

2023-03-05 10:57 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...new Set(arr)];
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2023-03-05 10:57 UTC, dosandk requested changes
решение `createGetter` следует поправить

2023-03-06 07:24 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-06 07:26 UTC, e-free commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...new Set(arr)];
Array.from более универсальный метод. Работает как со псевдомассивами, так и с итерируемыми объектами.  Спред-синтаксис работает только с итерируемыми объектами

2023-03-06 07:31 UTC, e-free commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  return getter;
undefined
Вероятно из-за мутации объекта.

2023-03-06 09:24 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const arr = path.split(".");
👍 good 
лайк за использование замікания

2023-03-06 09:25 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  return getter;
@e-free абсолютно точно, из-за "shift"
именно в таких ситуациях и заключается коварство мутаций, проблему очень сложно обнаружить сразу

2023-03-06 09:26 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...new Set(arr)];
@e-free точно, плюс у `Array.from` есть второй аргумент - ф-ция `map`

2023-03-06 09:27 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  let getter = (obj) => {
`const getter`

2023-03-06 09:27 UTC, dosandk approved these changes
good 👍

2023-03-06 09:28 UTC, merged

2023-03-06 10:32 UTC, e-free commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...new Set(arr)];
Спасибо